version: "3.8"

services:
  web:
    build: .
    command: sh -c "python3 manage.py migrate &&
                    python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./src:/code/src/
    ports:
      - "8888:8000"

  bot:
    build: .
    command: sh -c "python3 manage.py telegram_bot"
    depends_on:
      - db
      - web
    env_file:
      - .env
    volumes:
      - ./src:/code/src/

  db:
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  postgres:
  media:
