# Generated by Django 3.2.18 on 2023-10-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(unique=True, verbose_name='ID пользователя')),
                ('link', models.URLField(verbose_name='Ссылка на таблицу')),
            ],
        ),
    ]
