# Generated by Django 3.2.18 on 2023-05-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(verbose_name='ID пользователя')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('site', models.URLField(verbose_name='Ссылка на сайт')),
                ('site_alias', models.CharField(max_length=255, verbose_name='Сокращенный сайт')),
            ],
            options={
                'verbose_name': 'Пароль',
                'verbose_name_plural': 'Пароли',
            },
        ),
    ]
